name: Deployment

on:
  push:
    tags:        
      - '*'
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: deploy
        run: |
          echo ${{ github.sha }}
